analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: true
  errors:
    missing_required_param: warning
    missing_return: warning
  exclude:
    - lib/generated/locale_keys.g.dart
    - lib/data/network/*/*.g.dart
    - lib/network/api_client.g.dart
    - lib/*/*.gr.dart
    - lib/*/*.g.dart
    - pubspec.yaml
linter:
  rules:
    avoid_print: true
    omit_local_variable_types: false
    prefer_single_quotes: false
    lowercase_with_underscores: false
    always_declare_return_types: true
    always_use_package_imports: true
    annotate_overrides: true
    avoid_escaping_inner_quotes: true
    avoid_function_literals_in_foreach_calls: true
    avoid_implementing_value_types: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_return_types_on_setters: true
    avoid_returning_null_for_future: true
    avoid_returning_null_for_void: true
    avoid_setters_without_getters: true
    avoid_single_cascade_in_expression_statements: true
    avoid_shadowing_type_parameters: true
    avoid_types_as_parameter_names: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    await_only_futures: true
    cancel_subscriptions: true
    control_flow_in_finally: true
    curly_braces_in_flow_control_structures: true
    directives_ordering: true
    empty_constructor_bodies: true
    empty_statements: true
    exhaustive_cases: true
    file_names: true
    hash_and_equals: true
    iterable_contains_unrelated_type: true
    join_return_with_assignment: true
    library_prefixes: true
    list_remove_unrelated_type: true
    missing_whitespace_between_adjacent_strings: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    non_constant_identifier_names: true
    null_closures: true
    overridden_fields: true
    parameter_assignments: true
    prefer_asserts_in_initializer_lists: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_constructors_over_static_methods: true
    prefer_contains: true
    prefer_equal_for_default_values: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_function_declarations_over_variables: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_inlined_adds: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true
    prefer_null_aware_operators: true
    prefer_spread_collections: true
    prefer_typing_uninitialized_variables: true
    prefer_void_to_null: true
    recursive_getters: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    sort_pub_dependencies: true
    sort_unnamed_constructors_first: true
    test_types_in_equals: true
    throw_in_finally: true
    type_annotate_public_apis: true
    type_init_formals: true
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_getters_setters: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_statements: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    unrelated_type_equality_checks: true
    use_full_hex_values_for_flutter_colors: true
    use_function_type_syntax_for_parameters: true
    use_rethrow_when_possible: true
    valid_regexps: true
    void_checks: true
