name: fineance
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: 2.4.2
  bloc: 7.2.1
  bloc_test: 8.4.0
  cupertino_icons: 1.0.3
  easy_localization: 3.0.0
  equatable: 2.0.3
  fimber: 0.6.1
  flutter:
    sdk: flutter
  flutter_bloc: 7.3.0
  form_field_validator: 1.1.0
  get_it: 7.2.0
  hive: 2.0.4
  hive_flutter: 1.1.0
  local_auth: 1.1.8
  mocktail: 0.2.0
  provider: 6.0.1
  rive: 0.7.30

dev_dependencies:
  auto_route_generator: 2.4.1
  build_runner: 2.1.4
  flutter_test:
    sdk: flutter
  hive_generator: 1.1.1
  json_serializable: 5.0.2

flutter:
  uses-material-design: true

  assets:
  - assets/images/
  - assets/translations/
  - assets/animations/
